-- MySQL Script generated by MySQL Workbench
-- Wed 18 Oct 2017 09:05:29 AM COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alertfarm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alertfarm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alertfarm` DEFAULT CHARACTER SET utf8 ;
USE `alertfarm` ;

-- -----------------------------------------------------
-- Table `alertfarm`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertfarm`.`Clientes` (
  `idClientes` INT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(14) NOT NULL, 
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `idClientes_UNIQUE` (`idClientes` ASC),
  UNIQUE INDEX `username_UNIQUE` (`correo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertfarm`.`Temperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertfarm`.`Temperatura` (
  `idParametro` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NULL,
  `fecha` FLOAT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idParametro`),
  INDEX `fk_Parametro_Clientes_idx` (`Clientes_idClientes` ASC),
  CONSTRAINT `fk_Parametro_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `alertfarm`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alertfarm`.`Humedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertfarm`.`Humedad` (
  `idParametro` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NULL,
  `fecha` FLOAT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idParametro`),
  INDEX `fk_Parametro_Clientes_idx` (`Clientes_idClientes` ASC),
  CONSTRAINT `fk_Parametro_Clientes0`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `alertfarm`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

